//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Szkola.h
//  @ Date : 17.03.2026
//  @ Author : 
//
//


#if !defined(_SZKOLA_H)
#define _SZKOLA_H

#include <string>
#include "Nauczyciel.h"
using namespace std;

class Szkola {
public:
    Szkola(string Nazwa, string Adres, Nauczyciel Nauczyciel);
	void SetNazwa(string Nazwa);
	void SetAdres(string Adres);
    string GetNazwa();
    string GetAdres();
    Nauczyciel GetNauczyciel();
private:
	string Nazwa;
	string Adres;
    Nauczyciel Nauczyciel;
};

#endif  //_SZKOLA_H
