//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Szkola.cpp
//  @ Date : 17.03.2026
//  @ Author : 
//
//


#include "Szkola.h"
#include "Nauczyciel.h"

Szkola::Szkola(string Nazwa, string Adres, Nauczyciel Nauczyciel) {
    Nazwa = Nazwa;
    Adres = Adres;
    Nauczyciel = Nauczyciel;
}

void Szkola::SetNazwa(string Nazwa) {
    Nazwa = Nazwa;
}

void Szkola::SetAdres(string Adres) {
    Adres = Adres;
}

string Szkola::GetNazwa() {
    return Nazwa;
}

string Szkola::GetAdres() {
    return Adres;
}
Nauczyciel GetNauczyciel() {
    return Nauczyciel;
}

