//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Szkola.cpp
//  @ Date : 17.03.2026
//  @ Author : 
//
//


#include "Szkola.h"
#include "Nauczyciel.h"
#include <iostream>

using namespace std;

Szkola::Szkola(string Nazwa, string Adres, Nauczyciel* p_nauczyciel) {
    this->Nazwa = Nazwa;
    this->Adres = Adres;
    this->nauczyciel = p_nauczyciel;
}

void Szkola::SetNazwa(string Nazwa) {
    Nazwa = Nazwa;
}

void Szkola::SetAdres(string Adres) {
    Adres = Adres;
}

string Szkola::GetNazwa() {
    return Nazwa;
}

string Szkola::GetAdres() {
    return Adres;
}
Nauczyciel* Szkola::GetNauczyciel(){
    return nauczyciel;
}

////////////////////////////////////////////////////////////

int main()
{
    Nauczyciel* N = new Nauczyciel("Adam", "Kowal", 123456789, "Matematyk", 1500.99);

    Szkola* S = new Szkola("LO", "Aleja 1", N);

    cout<<"Nazwa: "<<S->GetNazwa()<<" | Adres: "<<S->GetAdres()<<" "<<"\n";
    cout<<"Nauczyciel: "<<S->GetNauczyciel()->GetImie()<<" "<<S->GetNauczyciel()->GetNazwisko()<<"\n";

    cin.get();

    return 0;
}
